---
management:
  port:                     8081
  security:
    role:                   ADMIN
    enabled:                true

server:
  port:                     8080

secure:
    port:                   8443

spring:
  datasource:
    initialize:             true

  jackson:
    serialization:
      INDENT_OUTPUT:        true

#http:
#  mappers:
#    jsonPrettyPrint:        true

---
spring:
  profiles:                 test

  jpa:
    hibernate:
      ddl-auto:             create-drop
    generate-ddl:           true
    show-sql:               true

---
spring:
  profiles:                 postgres

  jpa:
    hibernate:
      ddl-auto:             update
    database-platform:      org.hibernate.dialect.PostgreSQLDialect
    generate-ddl:           true
    show-sql:               true

  datasource:
    driverClassName:        org.postgresql.Driver


---
spring:
  profiles:                 mysql

  jpa:
    hibernate:
      ddl-auto:             update
    database-platform:      org.hibernate.dialect.MySQLDialect
    generate-ddl:           true
    show-sql:               true

  datasource:
    driverClassName:        com.mysql.jdbc.Driver
